### ISSUE TITLE
Overrides `resizeWidth` behavior in Chrome with incorrect behavior

### ISSUE THREAD

**Issue by josephrocca** [Kaiido/createImageBitmap#2]
Here are two minimal examples to visit in Chrome:
1. Without polyfill script: https://jsbin.com/yuwinizumi/edit?html,output
2. With polyfill script: https://jsbin.com/wilibaquqa/edit?html,output

Screenshot of (1):

![image](https://user-images.githubusercontent.com/1167575/163119671-ae07fe57-21e9-4599-b331-0a6002681083.png)

Screenshot of (2):

![image](https://user-images.githubusercontent.com/1167575/163119580-3cba1350-62ec-4202-99a4-f7e90863b9a1.png)

I see the same non-auto-proportional-resizing behavior on iOS.

Also, per the "Does this mean even my shiny Chromium browser will [...]" FAQ question I'd expect the polyfill to not interfere with Chrome unless there's an SVG blob passed in. I'm worried that it will affect Chrome performance if it's doing some other magic behind the scenes, even in browsers that don't need the polyfill.

Thanks for your work on this!

(Aside: Has WebKit implemented `resizeWidth`? I don't have an iOS device on hand to test, but I used a free 1 minute browserstack session and the polyfill-less jsbin above seemed to work correctly - didn't have time to properly look into it though. No support mentioned [here](https://bugs.webkit.org/show_bug.cgi?id=182424), but maybe in another issue? [MDN says](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap#browser_compatibility) it's unsupported.)

**Comment by Kaiido** [comment]
Wow thanks a lot for this!

The fact that we did use the polyfill for any Blob was a complete typo and somehow it's thanks to the resize bug that you found it... I got lazy and never really made extensive tests for the part of the code that is specific to the polyfill, I really have to take the time to do it.  

For the resize bug, I effectively completely missed this step and there is no single test in WPT for it. I will probably write one when I get more time.  

Regarding the browser support it actually did change consequently since I wrote that Readme page, I should update it too, but apparently Safari now has about the same support as Chrome minus SVGImageElement as source. Firefox also added support for resizeWidth and resizeHeight, not sure when.

So this makes this whole polyfill a lot less attractive I'm afraid (and glad at the same time).

Anyway, I applied quick fixes for both issues you found. Thanks again for letting me know about it.
